_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 11
                - 12
                - 45
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 12
                - 45
                - 49
                - 51
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.20
            "5": 0.19.0
            "6": 4.47.0
            "8":
                - 5
            "12": 0.19.0
            "13": darwin-arm64
model_config:
    value:
        batch_size: 4
        d_hidden: 1024
        d_pos: 20
        dropout_rate: 0.1
        intermediate_size: 1024
        n_layers: 5
        seq_len: 512
        vocab_size: 50257
num_epochs:
    value: 10
seed:
    value: 42
